spring.application.name=helloSpringBoot

server.servlet.context-path=/helloSpringBoot

# expose all actuator endpoints over HTTP : 모든 actuator 엔드포인트를 노출
management.endpoints.web.exposure.include=*
# management.endpoints.web.exposure.exclude=env, beans

management.info.env.enabled=true

info.app.name=My Super Cool App
info.app.description=A crazy and fun app, yoohoo!
info.app.version=1.0.0

app.professor = WonJun Lee
app.courseName = Web Framework

logging.level.kr.ac.hansung = debug